### ISSUE TITLE
How to get/refer to title of a Paper similar to `\nameref`? 

### ISSUE THREAD

**Issue by fzeiser** [uio-latex/phduio-article-based#2]
How can I refer to the title of a `Paper` that is included in the thesis (similar to what is retrieved by the TOC)?

Let us assume that I want to refer to the title of paper I, which is defined here:
https://github.com/martinhelso/phduio-article-based/blob/fc275d11dbc93606055d32803123c28b0e8b95ca/sections/paperI.tex#L7

The dummy code I think of looks like this:
``` latex
In the paper with the title \nameref{pap:first} we find out many things.
```
Which I would like to produce:
> In the paper with the title The First Paper we find out many things.

The `nameref` command would work for chapter and section names, however when I tried this for the paper title, I got the title of the thesis returned (in the template this is called *Working title* )

**Comment by martinhelso** [comment]
This is now fixed in
https://github.com/martinhelso/phduio-article-based/blob/8693f7ed063197885c4c59a22990e351ced2320b/phduio.cls#L318-L325
